profile: private
region: us-east-1
configuration:
  name: aws-price-api
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_handler.lambda_handler
  description: "Get specified data from AWS Price List API"
  timeout: 60
  memory_size: 512
secret:
  key: {{ env['AWS_KMS_KEY_ID'] }}
  cipher_texts: {}
